name: Integração Contínua Cypress Tests TCC

on:
  schedule:
    - cron: '0 11,15,21 * * *' 
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  cypress-tests-desktop:
    needs: eslint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' 
      - name: Install dependencies
        run: npm ci
      - name: Run end-to-end tests on desktop viewport 🧪
        run: npm run test:cloud
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
