name: Integração Contínua Cypress Tests TCC

on:
  schedule:
    - cron: '0 11 * * *' 

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' 

      - name: Instalar Dependências
        run: npm ci

      - name: Rodar Testes Cypress
        run: npm test
